services:
  - type: web
    name: institutional-cms
    env: node
    buildCommand: |
      echo "Installing dependencies..."
      npm install
      echo "Building the application..."
      npm run build
      echo "Build completed. Contents of dist directory:"
      ls -la dist/
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add other environment variables from your .env file here
      # Make sure to set them in Render's dashboard as well
    plan: free
